import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { FiArrowUpRight, FiCheck } from 'react-icons/fi'
import ServiceCard from '../components/ServiceCard'
import CtaSection from '../components/CtaSection'
import { reviews, services, technologyGroups } from '../data'

export default function Home() {
  return <>
    <section className="hero-page"><div className="hero-grid" /><div className="hero-copy"><span className="eyebrow">Virexo Innovations / Digital systems studio</span><h1>Build the <em>signal</em> inside your next big idea.</h1><p>We create thoughtful digital products, intelligent workflows, and interfaces that help ambitious teams move from complexity to clarity.</p><div className="hero-actions"><Link className="button-primary" to="/services">Explore our services <FiArrowUpRight /></Link><Link className="button-ghost" to="/contact">Request a consultation <FiArrowUpRight /></Link></div><div className="hero-proof"><span><b>01</b> Strategy with substance</span><span><b>02</b> Technology with purpose</span></div></div><motion.div className="hero-orbit" animate={{ rotate: 360 }} transition={{ duration: 26, repeat: Infinity, ease: 'linear' }}><div className="orbit-core"><span>VX</span><small>Ideas / Systems / Motion</small></div><i /><i /><i /></motion.div><div className="hero-coordinate">33.6844° N / 73.0479° E<br /><span>Digital territory, open for ideas</span></div></section>
    <section className="intro-strip"><span>Independent digital partner</span><p>Virexo works where business ambition meets the messy, exciting work of making something real.</p><Link to="/about">Why Virexo <FiArrowUpRight /></Link></section>
    <section className="home-section cv-drop-section" id="careers"><div className="section-heading"><span className="eyebrow">Work with Virexo</span><h2>Bring your perspective to the <em>next idea.</em></h2><p>Drop your CV and tell us where you can make useful work happen. We review every application with care.</p></div><form className="cv-drop-form" data-cv-form><div className="cv-drop-fields"><label>Full name<input name="name" type="text" required placeholder="Your full name" /></label><label>Email<input name="email" type="email" required placeholder="you@company.com" /></label><label>Specialization<input name="specialization" type="text" required placeholder="e.g. Product design" /></label><label>Experience<select name="experience" required><option value="">Select experience</option><option>0-2 years</option><option>3-5 years</option><option>6+ years</option></select></label></div><label className="cv-dropzone" data-cv-dropzone><input name="resume" type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required /><span className="cv-drop-icon">↑</span><strong>Drop your CV here or browse</strong><small>PDF, DOC, or DOCX up to 5MB</small><span className="cv-file-name" data-cv-file>Nothing selected yet</span></label><div className="cv-drop-actions"><button className="button-primary" type="submit">Send my CV <FiArrowUpRight /></button><p className="cv-status" data-cv-status aria-live="polite"></p></div></form></section>
    <section className="home-section services-preview"><div className="section-heading"><span className="eyebrow">01 / Capabilities</span><h2>Three ways to create <em>forward motion.</em></h2><p>Focused expertise, brought together around the outcome your business needs next.</p></div><div className="service-preview-grid">{services.map((service) => <ServiceCard key={service.id} service={service} />)}</div><Link className="inline-link" to="/services">See all service detail <FiArrowUpRight /></Link></section>
    <section className="stats-band"><div><span>01</span><strong data-stat-value="4">0</strong><p>Product disciplines</p></div><div><span>02</span><strong data-stat-value="12">0</strong><p>Technology layers</p></div><div><span>03</span><strong data-stat-value="1">0</strong><p>Clear working rhythm</p></div><div><span>04</span><strong>∞</strong><p>Room to evolve</p></div></section>
    <section className="home-section project-preview"><div className="section-heading split-heading"><div><span className="eyebrow">02 / Selected work</span><h2>Useful things, <em>made visible.</em></h2></div><Link className="inline-link" to="/projects">View portfolio <FiArrowUpRight /></Link></div><div className="featured-project"><div className="project-visual project-visual-large">VX / 01 <span>Virexo / digital home</span></div><div><span className="eyebrow-number">Web Development / Product Systems</span><h3>Virexo Innovations Business Website</h3><p>A new digital home designed to make a technology company’s thinking, capability, and next steps easier to understand.</p><ul>{['Responsive experience', 'Live operational signals', 'Built for future pages'].map((item) => <li key={item}><FiCheck />{item}</li>)}</ul><Link className="inline-link" to="/projects">Read the case study <FiArrowUpRight /></Link></div></div></section>
    <section className="home-section review-preview"><div className="section-heading"><span className="eyebrow">03 / Sample voices</span><h2>Good work should feel <em>clear.</em></h2></div><div className="review-preview-grid">{reviews.slice(0, 3).map((review) => <blockquote key={review.id}><div className="stars">{'★'.repeat(review.rating)}</div><p>“{review.text.replace('Sample review: ', '')}”</p><footer><strong>{review.name}</strong><span>{review.role}</span></footer></blockquote>)}</div><p className="sample-label">Sample content for demonstration purposes.</p></section>
    <section className="tech-band"><div><span className="eyebrow">04 / Technology stack</span><h2>The right tools are the ones that make the work <em>better.</em></h2></div><div className="tech-marquee">{technologyGroups.flatMap((group) => group.items).map((technology) => <span key={technology.name}>{technology.name}</span>)}</div></section>
    <CtaSection title="Have a useful problem? Let's give it shape." />
  </>
}
